// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package internal

var TableNames = struct {
	Orders string
}{
	Orders: "orders",
}
